name: Create Pull Request for DSA Branches

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - 'dsa/**'  # Trigger only on push to dsa/ prefixed branches

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          base: main  # PR target base branch
          branch: ${{ github.ref_name }}  # Source branch is the branch that triggered the workflow
          title: "DSA: ${{ github.ref_name }}"
          body: |
            This pull request contains DSA updates from branch **${{ github.ref_name }}**.
            - Automatically created using GitHub Actions.
          delete-branch: false
