name: Auto Create PR for DSA Branches

on:
  push:
    branches:
      - 'dsa/**' # Trigger on push to any branch matching dsa/* (dsa/feature, dsa/bugfix, etc.)
  create:
    branches:
      - 'dsa/**' # Trigger when a new branch matching dsa/* is created

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to read repo contents
      pull-requests: write # Needed to create and update pull requests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auto create PR
        id: create_pr # Give this step an ID to reference its outputs
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Use the built-in GITHUB_TOKEN
          # Optional: Use a specific commit message or PR title
          commit-message: 'feat: Automate PR for branch ${{ github.ref_name }}'
          title: 'feat: Add changes from ${{ github.ref_name }}'
          body: |
            This pull request was automatically generated by GitHub Actions
            due to a push or creation of a branch matching `dsa/*`.

            **Branch:** `${{ github.ref_name }}`
            **Commit:** `${{ github.sha }}`
          base: main # The branch you want to merge into
          head: ${{ github.ref_name }} # The current branch that triggered the workflow
          labels: | # Optional: Add labels to the PR
            automation
            dsa-changes
          assignees: ${{ github.actor }} # Optional: Assign the PR to the committer
          # Optional: review-requested: 'your-team-slug/reviewers' # Request reviews from a team or individual

      - name: Output PR URL (for debugging/logging)
        if: steps.create_pr.outputs.pull-request-url
        run: |
          echo "Pull Request created: ${{ steps.create_pr.outputs.pull-request-url }}"
