name: Auto PR from dsa/* to main

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - 'dsa/**'  # Trigger on any push to dsa/* branches

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "sync: changes from ${{ github.ref_name }}"
          title: "Auto PR: '${{ github.ref_name }}' → 'main'"
          body: |
            This pull request was automatically created from the branch `${{ github.ref_name }}` to `main`.

            Please review and merge if everything looks good.
          base: main
          branch: ${{ github.ref_name }}
          commit-mode: append  # Avoids force-push or rebase
          delete-branch: false


