name: Create PR to main from dsa/*

permissions:
  contents: write
  pull-requests: write


on:
  push:
    branches:
      - 'dsa/**'

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed to compare history

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Get current branch name
      id: get_branch
      run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

    - name: Check for new commits compared to main
      id: check
      run: |
        COMMITS=$(git rev-list --count origin/main..${{ steps.get_branch.outputs.branch }})
        echo "ahead_by=$COMMITS" >> $GITHUB_OUTPUT

    - name: Install GitHub CLI
      run: sudo apt install -y gh

    - name: Authenticate GitHub CLI
      run: echo "${{ secrets.GH_PAT }}" | gh auth login --with-token

    - name: Create Pull Request
      if: steps.check.outputs.ahead_by != '0'
      run: |
        gh pr create \
          --base main \
          --head ${{ steps.get_branch.outputs.branch }} \
          --title "Auto PR: ${{ steps.get_branch.outputs.branch }} → main" \
          --body "This PR was created automatically on push to ${{ steps.get_branch.outputs.branch }}."
      
    - name: Enable Auto-Merge
      if: steps.check.outputs.ahead_by != '0'
      run: |
        PR_URL=$(gh pr view ${{ steps.get_branch.outputs.branch }} --json url -q .url)
        gh pr merge "$PR_URL" --merge --auto
